language: node_js
node_js:
  - lts/*

before_install:
  - "export CHROME_BIN=/usr/bin/google-chrome"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - gulp build
  - gulp test --coverage

sudo: required
dist: trusty

addons:
  chrome: stable
  firefox: latest
